# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 06:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='created',
        ),
    ]
