# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_profile_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourite_quote',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
