# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 14:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shots', '0005_friend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('from_friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_set', to=settings.AUTH_USER_MODEL)),
                ('to_friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_friend_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='friend',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='following',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='user_from',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='user_to',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
