# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0006_auto_20170806_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='from_friend',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='to_friend',
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
